#!/usr/bin/env zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

if [[ "$(hostname)" == "theo-planet" ]]; then
    source $ZDOTDIR/.zshrc_work
fi

# Lazy-load (autoload) Zsh function files from a directory.
ZFUNCDIR=$ZDOTDIR/.zfunctions
fpath=($ZFUNCDIR $fpath)
autoload -Uz $ZFUNCDIR/*(.:t)

# Set any zstyles you might use for configuration.
[[ ! -f $ZDOTDIR/.zstyles ]] || source $ZDOTDIR/.zstyles

# Clone antidote if necessary.
if [[ ! -d $ZDOTDIR/.antidote ]]; then
  git clone https://github.com/mattmc3/antidote $ZDOTDIR/.antidote
fi

# Create an amazing Zsh config using antidote plugins.
source $ZDOTDIR/.antidote/antidote.zsh
antidote load

# Source anything in .zshrc.d.
for _rc in $ZDOTDIR/.zshrc.d/*.zsh; do
  # Ignore tilde files.
  if [[ $_rc:t != '~'* && $_rc:t != *"_work"* ]]; then
    source "$_rc"
  fi
done
unset _rc

# Enable fzf tab completion
enable-fzf-tab


. "$HOME/.local/share/../bin/env"
