#!/bin/bash

left_pane_id=$(wezterm cli get-pane-direction left)
if [ -z "${left_pane_id}" ]; then
  left_pane_id=$(wezterm cli split-pane --left --percent 20)
fi
left_program=$(wezterm cli list | awk -v pane_id="$left_pane_id" '$3==pane_id { print $6 }')
if [ "$left_program" != "br" ]; then
  echo "br" | wezterm cli send-text --pane-id $left_pane_id --no-paste && wezterm cli activate-pane --pane-id $left_pane_id
fi
