[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "markdown"
language-servers = [ "markdown-oxide", "marksman" ]

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
