#!/bin/bash

sedpattern='s/'
sedpattern+='case"browser-backward":\(\w.*\)(-1,\w.webContents);break;case"browser-forward":\(\w.*\)(1,\w.webContents);break/'
sedpattern+='case"browser-backward":\1( 0,\w.webContents);break;case"browser-forward":\2(0,\w.webContents);break/'
sudo sed -i "$sedpattern" /usr/lib/slack/resources/app.asar
