#! /bin/sh

#autostart
exec $HOME/.config/bspwm/autostartbspwm.sh &

#workspaces
bspc monitor DP-0 -d WWW DEV GAMES MEDIA ETC

#window settings
bspc config border_width 5
bspc config window_gap 10
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0

#colours
bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#3b4252"
bspc config presel_feedback_color "#b48ead"


bspc config focus_follows_pointer true
bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle false