#!/bin/bash

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc edge_gap           35 0 0 0

# Set decoration colors
berryc focus_color         "#5e81ac"
berryc unfocus_color       "#3b4252"
berryc inner_focus_color   "#81a1c1"
berryc inner_unfocus_color "#2e3440"
berryc text_focus_color    "#eceff4"
berryc text_unfocus_color  "#d8dee9"

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Iosevka"

$HOME/.config/polybar/launch.sh
nitrogen --restore; sleep 1; picom -b
xrandr --rate 144
udiskie &
lxpolkit &
dunst &
sxhkd &